# Generated by Django 3.2.16 on 2022-12-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0023_paid_student_purchased_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certi_id', models.CharField(max_length=20, unique=True)),
                ('cert_name', models.CharField(max_length=150)),
                ('cert_for', models.CharField(max_length=200)),
                ('cert_collegeName', models.CharField(max_length=250)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
