# Generated by Django 3.2.16 on 2022-12-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0024_certi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certi',
            name='certi_id',
            field=models.CharField(default='EAAC42FDB184459', max_length=20, unique=True),
        ),
    ]
